### ISSUE TITLE
マージ方法の自動通知システムを追加

### ISSUE THREAD

**Issue by taka-123** [taka-123/laravel_nuxt_postgre_template#11]
## 概要
develop → main のPRで自動的にマージ方法を通知し、ミスを防ぐ。

## やること
1. PRテンプレート追加（全PR共通）
2. GitHub Actions追加（develop→mainの時だけ動く）

## タスク
- [ ] `.github/pull_request_template.md` を追加
- [ ] `.github/workflows/merge-reminder.yml` を追加
- [ ] テスト用PRで動作確認

### 1. PRテンプレート
```markdown
## 概要
<!-- 何を変更したか簡潔に -->

## 関連Issue
closes #

## 変更種別
- [ ] feat: 新機能
- [ ] fix: バグ修正
- [ ] chore: その他

## セルフチェック
- [ ] 動作確認済み
<!-- ↑ PR作成者がチェックしてください -->
```

### 2. GitHub Actions
```yaml
# .github/workflows/merge-reminder.yml
name: Merge Reminder

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  remind:
    if: github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '## 📘 リリースPRです\n\n**必ず `Create a merge commit` を使用してください**\n\n（Squash mergeは使用しないでください）'
            })
```
