### ISSUE TITLE
mise導入による開発環境管理の改善

### ISSUE THREAD

**Issue by taka-123** [taka-123/laravel_nuxt_postgre_template#42]
## 概要

開発環境のツールバージョン管理を統一するため、miseを導入したいと思います。
mise を使わない開発者にも悪影響を与えず、使う開発者には便利な環境を提供できます。

### .mise.toml の追加

```toml
[tools]
node = "22"    # package.json の engines と合わせる
php = "8.3"    # backend/composer.json と合わせる
```

### 対象ツール

- **node**: フロントエンド開発に必要
- **php**: バックエンド開発に必要

### 対象外ツール

- **composer**: miseで管理不可（システムグローバルが一般的）
- **pnpm**: 利用可能だが、このプロジェクトはnpm/yarn使用
- **postgres**: 利用可能だが、このプロジェクトはDocker管理

## メリット

1. **開発環境の統一**: チーム開発でのバージョン不一致を防止
2. **セットアップの簡素化**: `mise install` だけで必要なツールが揃う
3. **既存環境との共存**: volta、asdf、phpenv ユーザーも影響なし
4. **無害**: mise を使わない人は単純にファイルを無視

## 追加作業

- README.md に mise の使い方を軽く説明
- 既存のツール管理方法との共存について説明

## 参考

- [mise 公式サイト](https://mise.jdx.dev/)
- 類似ツール: asdf, volta, nodenv, phpenv

## 優先度

Low - 開発体験の向上だが必須ではない
